name: HCCooldown
main: plugin.HCCooldown
version: 1.1.1
api-version: 1.13
commands:
  cooldown:
    description: Check all cooldowns currently running.
    usage: /cooldown <player>
  cdrefresh:
    description: Refresh all cooldowns currently running.
    usage: /cdrefresh
